# Generated by Django 4.1.7 on 2023-04-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_pack', '0002_proyecto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento_no_funcional',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
