# Generated by Django 4.1.7 on 2023-04-21 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_pack', '0003_alter_requerimiento_no_funcional_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='preguntas_factores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=150)),
                ('p2', models.CharField(max_length=150)),
                ('p3', models.CharField(max_length=150)),
                ('p4', models.CharField(max_length=150)),
                ('p5', models.CharField(max_length=150)),
                ('p6', models.CharField(max_length=150)),
                ('p7', models.CharField(max_length=150)),
                ('p8', models.CharField(max_length=150)),
                ('p9', models.CharField(max_length=150)),
                ('p10', models.CharField(max_length=150)),
                ('p11', models.CharField(max_length=150)),
                ('p12', models.CharField(max_length=150)),
                ('p13', models.CharField(max_length=150)),
                ('p14', models.CharField(max_length=150)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_pack.proyecto')),
            ],
        ),
    ]
