# Generated by Django 4.1.7 on 2023-05-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_pack', '0006_alter_proyecto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='lenguaje',
            field=models.CharField(max_length=500),
        ),
    ]
