# Generated by Django 4.1.7 on 2023-05-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Calculo', '0002_alter_puntosfuncion_puntos_funcion_ajustados_kldc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDCxPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C', models.SmallIntegerField()),
                ('CPP', models.SmallIntegerField()),
                ('JAVA', models.SmallIntegerField()),
                ('JAVASCRIPT', models.SmallIntegerField()),
                ('JSP', models.SmallIntegerField()),
                ('SQL', models.SmallIntegerField()),
                ('PYTHON', models.SmallIntegerField()),
                ('CSHARP', models.SmallIntegerField()),
                ('NET', models.SmallIntegerField()),
                ('GO', models.SmallIntegerField()),
                ('PHP', models.SmallIntegerField()),
            ],
        ),
    ]
